stages:
  data_injection:
    cmd: python src/data/data_injection.py
    deps:
      - src/data/data_injection.py

  feature_extraction:
    cmd: python src/feature_engineering/feature_extraction.py
    deps:
      - src/data/data_injection.py
      - src/feature_engineering/feature_extraction.py
    params:
      - feature_extraction.KMeans.n_clusters
      - feature_extraction.KMeans.init
      - feature_extraction.KMeans.random_state
      - feature_extraction.resample_data.alpha
    outs:
      - data/processed/resampled_df.csv
      - src/model/scaler.joblib
      - src/model/kmeans.joblib

  feature_processing:
    cmd: python src/feature_engineering/feature_processing.py
    deps:
      - src/feature_engineering/feature_processing.py
      - data/processed/resampled_df.csv
    outs:
      - data/processed/training_df.csv
      - data/processed/testing_df.csv

  model_training:
    cmd: python src/model/train.py
    deps: 
      - src/model/train.py    
      - data/processed/training_df.csv
    outs: 
      - src/model/preprocessor.joblib
      - src/model/model.joblib

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps: 
      - src/model/model_evaluation.py
      - data/processed/training_df.csv
      - data/processed/testing_df.csv
      - src/model/model.joblib
      - src/model/preprocessor.joblib
    outs:
      - run_information.json

  register_model:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - run_information.json

  


   

      


      

    


    

